#!/bin/bash

###############################################################################
# Installation script for gogs.
#
# This script is executed during the build of the docker image.
###############################################################################

GOGS_VERSION="v0.9.13"

INSTALL_DIR="/home/gogs/gogs"
DATA_DIR="/home/gogs/data"
LOG_DIR="/home/gogs/data/log"
SETUP_DIR="/app/setup"

# add gogs user
adduser --disabled-login --gecos 'Gogs' gogs
passwd -d gogs

# add git user
adduser --disabled-login --gecos 'gogsgit' git
passwd -d git

##
# TODO: ssh setup
##

# create symlink to ${DATA_DIR}/dotfiles/.ssh
rm -rf /home/gogs/.ssh /home/git/.ssh
sudo -u gogs -H ln -s ${DATA_DIR}/ssh /home/gogs/.ssh
sudo -u git -H ln -s ${DATA_DIR}/ssh /home/git/.ssh

# Install gogs, use local copy if available
mkdir -p /home/gogs

if [ -f ${SETUP_DIR}/gogs-${GOGS_VERSION}.tar.bz2 ]
then
    tar -C /home/gogs -xvf ${SETUP_DIR}/gogs-${GOGS_VERSION}.tar.bz2
else
    wget -nv "https://github.com/gogits/gogs/releases/download/${GOGS_VERSION}/linux_amd64.zip" -O /tmp/gogs.zip
    unzip /tmp/gogs.zip -d /home/gogs
fi

# Fix permissions
chown -R gogs:gogs ${INSTALL_DIR}
chmod 755 ${INSTALL_DIR}
chmod a+x ${INSTALL_DIR}/gogs

# move supervisord.log file to ${LOG_DIR}/supervisor/
sed 's|^logfile=.*|logfile='"${LOG_DIR}"'/supervisor/supervisord.log ;|' -i /etc/supervisor/supervisord.conf

# link gogs directories
cd ${INSTALL_DIR}
rm -rf ./log ./data ./custom

ln -sf ${LOG_DIR}/gogs ./log
ln -sf ${DATA_DIR}/gogs/data ./data
ln -sf ${DATA_DIR}/gogs/custom ./custom

# setup log rotation for gogs application logs
cat > /etc/logrotate.d/gogs <<EOF
${LOG_DIR}/gogs/*.log {
  weekly
  missingok
  rotate 52
  compress
  delaycompress
  notifempty
  copytruncate
}
EOF

# configure supervisord log rotation
cat > /etc/logrotate.d/supervisord <<EOF
${LOG_DIR}/supervisor/*.log {
  weekly
  missingok
  rotate 52
  compress
  delaycompress
  notifempty
  copytruncate
}
EOF

# configure supervisord to start gogs
cat > /etc/supervisor/conf.d/gogs.conf <<EOF
[program:gogs]
priority=20
directory=${INSTALL_DIR}
command=${INSTALL_DIR}/start.sh
user=gogs
environment = HOME="/home/gogs", USER="gogs"
autostart=true
autorestart=true
startretries=10
startsecs=10
stdout_logfile=${LOG_DIR}/supervisor/%(program_name)s.log
stderr_logfile=${LOG_DIR}/supervisor/%(program_name)s.log
EOF

# export Gogs custom config dir
echo "export GOGS_CUSTOM=${DATA_DIR}/gogs/custom" >> /home/gogs/.bashrc

# start script for gogs
cat > ${INSTALL_DIR}/start.sh <<EOF
#!/bin/bash

IFS='
        '
PATH=/bin:/usr/bin:/usr/local/bin
USER=gogs
HOME=/home/gogs
export USER HOME PATH

cd "${INSTALL_DIR}" && exec ./gogs web
EOF

chown gogs:gogs ${INSTALL_DIR}/start.sh
chmod a+x ${INSTALL_DIR}/start.sh

# cleanup
rm -rf /var/lib/apt/lists/*
