#!/bin/bash

INSTALL_DIR=${INSTALL_DIR:-/home/gogs/gogs}
DATA_DIR=${DATA_DIR:-/home/gogs/data}
LOG_DIR=${LOG_DIR:-/home/gogs/data/log}

SETUP_DIR="/app/setup"
SETUP_CONFIG_DIR="${SETUP_DIR}/config"

DB_HOST=${DB_HOST:-}
DB_PORT=${DB_PORT:-}
DB_NAME=${DB_NAME:-}
DB_USER=${DB_USER:-}
DB_PASS=${DB_PASS:-}
DB_TYPE=${DB_TYPE:-mysql}
DB_PATH=${DB_PATH:-}
DB_SSL_MODE=${DB_SSL_MODE:-disable}

GOGS_PORT=${GOGS_PORT:-3000}
GOGS_PROTOCOL=${GOGS_PROTOCOL:-https}
GOGS_DOMAIN=${GOGS_DOMAIN:-localhost}
GOGS_ROOT_URL=${GOGS_ROOT_URL:-localhost}
GOGS_INSTALL_LOCK=${GOGS_INSTALL_LOCK:-true}
GOGS_SECRET_KEY=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 50 | head -n 1)
GOGS_DISABLE_REGISTRATION=${GOGS_DISABLE_REGISTRATION:-false}

MAILER_ENABLED=${MAILER_ENABLED:false}
MAILER_HOST=${MAILER_HOST:-}
MAILER_FROM=${MAILER_FROM:-}
MAILER_USER=${MAILER_USER:-}
MAILER_PASS=${MAILER_PASS:-}

# Gogs folders
GOGS_GIT_DIR=${DATA_DIR}/git
GOGS_DATA_DIR=${DATA_DIR}/gogs
GOGS_CUSTOM_DIR=${DATA_DIR}/gogs/custom
GOGS_CUSTOM_CONF_DIR=${DATA_DIR}/gogs/custom/conf

# is a mysql or postgresql database linked?
# port 3306 and 5432 respectively.
if [ -n "${MYSQL_PORT_3306_TCP_ADDR}" ]; then
  DB_TYPE=mysql
  DB_HOST=${DB_HOST:-${MYSQL_PORT_3306_TCP_ADDR}}
  DB_PORT=${DB_PORT:-${MYSQL_PORT_3306_TCP_PORT}}

  # support for linked sameersbn/mysql image
  #DB_USER=${DB_USER:-${MYSQL_ENV_DB_USER}}
  #DB_PASS=${DB_PASS:-${MYSQL_ENV_DB_PASS}}
  #DB_NAME=${DB_NAME:-${MYSQL_ENV_DB_NAME}}

  # support for linked orchardup/mysql and centurylink/mysql image
  #DB_USER=${DB_USER:-${MYSQL_ENV_MYSQL_USER}}
  #DB_PASS=${DB_PASS:-${MYSQL_ENV_MYSQL_PASSWORD}}
  #DB_NAME=${DB_NAME:-${MYSQL_ENV_MYSQL_DATABASE}}
elif [ -n "${POSTGRESQL_PORT_5432_TCP_ADDR}" ]; then
  DB_TYPE=postgres
  DB_HOST=${DB_HOST:-${POSTGRESQL_PORT_5432_TCP_ADDR}}
  DB_PORT=${DB_PORT:-${POSTGRESQL_PORT_5432_TCP_PORT}}

  # support for linked official postgres image
  #DB_USER=${DB_USER:-${POSTGRESQL_ENV_POSTGRES_USER}}
  #DB_PASS=${DB_PASS:-${POSTGRESQL_ENV_POSTGRES_PASS}}
  #DB_NAME=${DB_NAME:-${DB_USER}}

  # support for linked sameersbn/postgresql image
  #DB_USER=${DB_USER:-${POSTGRESQL_ENV_DB_USER}}
  #DB_PASS=${DB_PASS:-${POSTGRESQL_ENV_DB_PASS}}
  #DB_NAME=${DB_NAME:-${POSTGRESQL_ENV_DB_NAME}}

  # support for linked orchardup/postgresql image
  #DB_USER=${DB_USER:-${POSTGRESQL_ENV_POSTGRESQL_USER}}
  #DB_PASS=${DB_PASS:-${POSTGRESQL_ENV_POSTGRESQL_PASS}}
  #DB_NAME=${DB_NAME:-${POSTGRESQL_ENV_POSTGRESQL_DB}}

  # support for linked paintedfox/postgresql image
  #DB_USER=${DB_USER:-${POSTGRESQL_ENV_USER}}
  #DB_PASS=${DB_PASS:-${POSTGRESQL_ENV_PASS}}
  #DB_NAME=${DB_NAME:-${POSTGRESQL_ENV_DB}}
fi

##
## For the sake of getting the quick start guide to work,
## we attempt to spin up a postgresql container if possible.
##
## NOTE: this is only meant for getting the quick start guide to work .
##
if [ -z "${DB_HOST}" -a -n "$(which docker)" -a -S /var/run/docker.sock ]; then
  echo "Database connection details not specified."
  echo "Will try to spin up a new postgresql image with the name postgresql-gogs."
  echo "Please manually configure the database connection in production."
  case "$(docker inspect --format {{.State.Running}} postgresql-gogs)" in
    true)
      echo "Using existing postgresql container..."
      ;;
    false)
      echo "Starting up existing postgresql container..."
      docker start postgresql-gogs >/dev/null
      ;;
    *)
      echo "Starting up a new postgresql container..."
      docker run --name='postgresql-gogs' -d \
        -e 'DB_USER=gogs' -e 'DB_PASS=password' -e 'DB_NAME=gogs_production' \
        sameersbn/postgresql:latest >/dev/null
      ;;
  esac
  DB_TYPE=postgres
  DB_HOST=$(docker inspect --format {{.NetworkSettings.IPAddress}} postgresql-gogs)
  DB_PORT=5432
  DB_USER=gogs
  DB_PASS=password
  DB_NAME=gogs_production
fi

# check if a database is specified and exit if no database is specified
if [ -z "${DB_HOST}" ]; then
  echo "Database connection details not specified."
  echo "  Using sqlite database."
  echo "  Do not use it in production."

  DB_TYPE="sqlite3"
  DB_HOST="127.0.0.1"
  DB_PORT="3306"
  DB_USER="root"
  DB_PASS=""
  DB_NAME="gogs_production"
  DB_PATH=data/gogs.db
fi

# use default port number if it is still not set
case "${DB_TYPE}" in
  mysql) DB_PORT=${DB_PORT:-3306} ;;
  postgres) DB_PORT=${DB_PORT:-5432} ;;
  sqlite3) ;;
  *)
    echo "ERROR: "
    echo "  Please specify the database type in use via the DB_TYPE configuration option."
    echo "  Accepted values are \"postgres\" or \"mysql\". Aborting..."
    exit 1
    ;;
esac

# set the default user and database
DB_NAME=${DB_NAME:-gogs_production}
DB_USER=${DB_USER:-root}

# populate dirs
# if [ ! -d ${DATA_DIR} ]; then

mkdir -p ${LOG_DIR} ${GOGS_CUSTOM_CONF_DIR} ${GOGS_DATA_DIR}/data ${GOGS_GIT_DIR}

# Fix permissions
chown -R gogs:gogs ${GOGS_DATA_DIR}
chmod 755 ${GOGS_DATA_DIR}
chown -R gogs:gogs ${GOGS_GIT_DIR}
chmod 755 ${GOGS_GIT_DIR}

# populate ${LOG_DIR}
mkdir -m 0755 -p ${LOG_DIR}/supervisor  && chown -R root:root ${LOG_DIR}/supervisor
mkdir -m 0755 -p ${LOG_DIR}/gogs        && chown -R gogs:gogs ${LOG_DIR}/gogs

# create the ssh directory
mkdir -p ${DATA_DIR}/ssh/
chown -R gogs:gogs ${DATA_DIR}/ssh

# fi

# generate ssh keys
if [ ! -e ${DATA_DIR}/ssh/id_rsa -o ! -e ${DATA_DIR}/ssh/id_rsa.pub ]; then
  echo "Generating SSH keys..."
  rm -rf ${DATA_DIR}/ssh/id_rsa ${DATA_DIR}/ssh/id_rsa.pub
  sudo -u gogs -H ssh-keygen -t rsa -N "" -f ${DATA_DIR}/ssh/id_rsa
fi

# make sure the ssh keys have the right ownership and permissions
chmod 600 ${DATA_DIR}/ssh/id_rsa ${DATA_DIR}/ssh/id_rsa.pub
chmod 700 ${DATA_DIR}/ssh

cd ${INSTALL_DIR}

####
# gogs configuration
####

# copy over the template configuration file
sudo -u gogs -H cp ${SETUP_CONFIG_DIR}/gogs/app.ini ${GOGS_CUSTOM_CONF_DIR}/app.ini

sudo -u gogs -H sed 's/{{DB_TYPE}}/'"${DB_TYPE}"'/' -i ${GOGS_CUSTOM_CONF_DIR}/app.ini
sudo -u gogs -H sed 's/{{DB_HOST}}/'"${DB_HOST}"':'"${DB_PORT}"'/' -i ${GOGS_CUSTOM_CONF_DIR}/app.ini
sudo -u gogs -H sed 's/{{DB_PORT}}/'"${DB_PORT}"'/' -i ${GOGS_CUSTOM_CONF_DIR}/app.ini
sudo -u gogs -H sed 's/{{DB_NAME}}/'"${DB_NAME}"'/' -i ${GOGS_CUSTOM_CONF_DIR}/app.ini
sudo -u gogs -H sed 's/{{DB_USER}}/'"${DB_USER}"'/' -i ${GOGS_CUSTOM_CONF_DIR}/app.ini
sudo -u gogs -H sed 's/{{DB_PASS}}/'"${DB_PASS}"'/' -i ${GOGS_CUSTOM_CONF_DIR}/app.ini
sudo -u gogs -H sed 's/{{DB_SSL_MODE}}/'"${DB_SSL_MODE}"'/' -i ${GOGS_CUSTOM_CONF_DIR}/app.ini
sudo -u gogs -H sed 's|{{DB_PATH}}|'"${DB_PATH}"'|' -i ${GOGS_CUSTOM_CONF_DIR}/app.ini

sudo -u gogs -H sed 's/{{HTTP_PORT}}/'"${GOGS_PORT}"'/' -i ${GOGS_CUSTOM_CONF_DIR}/app.ini
sudo -u gogs -H sed 's/{{PROTOCOL}}/'"${GOGS_PROTOCOL}"'/' -i ${GOGS_CUSTOM_CONF_DIR}/app.ini
sudo -u gogs -H sed 's|{{GIT_REPO}}|'"${GOGS_GIT_DIR}"'|' -i ${GOGS_CUSTOM_CONF_DIR}/app.ini
sudo -u gogs -H sed 's/{{DOMAIN}}/'"${GOGS_DOMAIN}"'/' -i ${GOGS_CUSTOM_CONF_DIR}/app.ini
sudo -u gogs -H sed 's/{{ROOT_URL}}/'"${GOGS_ROOT_URL}"'/' -i ${GOGS_CUSTOM_CONF_DIR}/app.ini
sudo -u gogs -H sed 's/{{SECRET_KEY}}/'"${GOGS_SECRET_KEY}"'/' -i ${GOGS_CUSTOM_CONF_DIR}/app.ini
sudo -u gogs -H sed 's/{{GOGS_INSTALL_LOCK}}/'"${GOGS_INSTALL_LOCK}"'/' -i ${GOGS_CUSTOM_CONF_DIR}/app.ini
sudo -u gogs -H sed 's/{{GOGS_DISABLE_REGISTRATION}}/'"${GOGS_DISABLE_REGISTRATION}"'/' -i ${GOGS_CUSTOM_CONF_DIR}/app.ini

sudo -u gogs -H sed 's/{{MAILER_ENABLED}}/'"${MAILER_ENABLED}"'/' -i ${GOGS_CUSTOM_CONF_DIR}/app.ini
sudo -u gogs -H sed 's/{{MAILER_HOST}}/'"${MAILER_HOST}"'/' -i ${GOGS_CUSTOM_CONF_DIR}/app.ini
sudo -u gogs -H sed 's/{{MAILER_FROM}}/'"${MAILER_FROM}"'/' -i ${GOGS_CUSTOM_CONF_DIR}/app.ini
sudo -u gogs -H sed 's/{{MAILER_USER}}/'"${MAILER_USER}"'/' -i ${GOGS_CUSTOM_CONF_DIR}/app.ini
sudo -u gogs -H sed 's/{{MAILER_PASS}}/'"${MAILER_PASS}"'/' -i ${GOGS_CUSTOM_CONF_DIR}/app.ini

# TODO: Handle templates
# Copy over the templates, if no templates are found
#test -d ${DATA_DIR}/templates || cp -ar ./templates ${DATA_DIR}
# Sync template folders
#rsync -rtv ${DATA_DIR}/templates ./templates/

# due to the nature of docker and its use cases, we allow some time
# for the database server to come online.
case "${DB_TYPE}" in
  mysql)
    prog="mysqladmin -h ${DB_HOST} -P ${DB_PORT} -u ${DB_USER} ${DB_PASS:+-p$DB_PASS} status"
    ;;
  postgres)
    prog=$(find /usr/lib/postgresql/ -name pg_isready)
    prog="${prog} -h ${DB_HOST} -p ${DB_PORT} -U ${DB_USER} -d ${DB_NAME} -t 1"
    ;;
esac

case "${DB_TYPE}" in
  "mysql" | "postgres")
    timeout=60
    echo -n "Waiting for database server to accept connections"
    while ! ${prog} >/dev/null 2>&1
    do
      timeout=$(expr $timeout - 1)
      if [ $timeout -eq 0 ]; then
        echo -e "\nCould not connect to database server. Aborting..."
        exit 1
      fi
      echo -n "."
      sleep 1
    done
    echo
esac

appStart () {
  # start supervisord
  exec /usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf
}

appHelp () {
  echo "Available options:"
  echo " app:start          - Starts the gogs server (default)"
  echo " app:help           - Displays the help"
  echo " [command]          - Execute the specified linux command eg. bash."
}

case "$1" in
  app:start)
    appStart
    ;;
  app:help)
    appHelp
    ;;
  *)
    if [ -x $1 ]; then
      $1
    else
      prog=$(which $1)
      if [ -n "${prog}" ] ; then
        shift 1
        $prog $@
      else
        appHelp
      fi
    fi
    ;;
esac

exit 0
